on:
  schedule:
    - cron: "* * * * 1"
  workflow_dispatch:
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: reports          
      - uses: foo-software/lighthouse-check-action@v4.0.0
        with:
          urls: https://helpfulengineering.org
          emulatedFormFactor: desktop
          outputDirectory: .
      - run: sudo apt install moreutils
      - id: results
        run: |
          mkdir -p ./reports
          for report in ./*.html; do
            time="$(sed 's:.*/report-\([0-9]*\)\.html:\1:g' <<< "$report")"
            cat "$report" | gunzip | jq "{\"$time\": {\"address\": .requestedUrl, \"seconds\": (.audits.interactive.numericValue / 1000) | floor}}"
            cat "$report" | perl -ne '/<script>window.__LIGHTHOUSE_JSON__ = (.*);<\/script>/ and print $1' | gzip > "./reports/$time.json.gz"
            echo "::set-output name=time::$time"
          done | jq -s add > ./performance.json
          jq -r '.[0].scores | keys[] as $key | "::set-output name=\($key)::\(.[$key])"' < ./results.json
          jq -s '.[0] + .[1]' ./reports.json ./results.json | sponge ./reports.json
          jq -s '.[0] + .[1]' ./data.json ./performance.json | sponge ./data.json
      - uses: EndBug/add-and-commit@v7
        with:
          message: Add reports
          add: "data.json reports.json reports"
      - run: |
          mkdir ./public
          git checkout origin/reports -- ./reports ./reports.json ./data.json
          git checkout origin/main -- './pages/*'
          mv ./reports ./reports.json ./data.json ./public
          mv ./pages/* ./public
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ github.token }}
          publish_branch: pages
          publish_dir: ./public
          force_orphan: true
      - uses: rtCamp/action-slack-notify@v2.1.0
        env:
          SLACK_CHANNEL: devops
          SLACK_USERNAME: Lighthouse
          SLACK_TITLE: Metrics for helpfulengineering.org
          SLACK_MESSAGE: |
            Accessibility: ${{ steps.results.outputs.accessibility }}%
            Best practices: ${{ steps.results.outputs.bestPractices }}%
            Performance: ${{ steps.results.outputs.performance }}%
            Progressive Web App: ${{ steps.results.outputs.progressiveWebApp }}%
            SEO: ${{ steps.results.outputs.seo }}%
            :book: <https://helpfulengineering.github.io/lighthouse/report.html?time=${{ steps.results.outputs.time }}|*Read the full report*>
          SLACK_FOOTER: |
            <https://github.com/helpfulengineering/lighthouse/blob/master/.github/workflows/report.yml|Click here to modify this bot.>
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          MSG_MINIMAL: true
