name: Lighthouse report

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@main

      - name: Checkout the reports branch
        run: |
          git fetch --all
          git checkout origin/reports
          
      - name: Retrieve the configuration
        id: configuration
        run: |
          git checkout origin/main -- "./configuration.json"
          echo ::set-output name=addresses::"$(jq -r '.addresses | join(",")' < ./configuration.json)"
          echo ::set-output name=emulated_form_factor::"$(jq -r '.emulated_form_factor' < ./configuration.json)"
          rm ./configuration.json
          
      - name: Create temporary directories
        run: |
          test -f ./reports.json || touch ./reports.json
          mkdir -p /tmp/artifacts ./reports
      - name: Generate the report
        uses: foo-software/lighthouse-check-action@master
        with:
          author: ${{ github.actor }}
          outputDirectory: /tmp/artifacts
          urls: "${{ steps.configuration.outputs.addresses }}"
          emulatedFormFactor: "${{ steps.configuration.outputs.emulated_form_factor }}"

      - name: Process the report results
        run: |
          jq -s '.[0] + .[1]' reports.json /tmp/artifacts/results.json > /tmp/artifacts/mix.json
          mv /tmp/artifacts/mix.json reports.json
          for report in /tmp/artifacts/*.html; do
            base="$(basename "$report")"; name="${base%.html}"; time="${name/lighthouse-report-}"
            perl -ne '/<script>window.__LIGHTHOUSE_JSON__ = (.*);<\/script>/ and print $1' "$report" |
              gzip > "/tmp/artifacts/$time.json.gz"
          done
          
          find /tmp/artifacts/*.json.gz | while read report; do
            base="$(basename "$report")"
            time="${base%.json.gz}"
            cat "$report" | gunzip | jq "{\"$time\": {\"address\": .requestedUrl, \"seconds\": (.audits.interactive.numericValue / 1000) | floor}}"
          done | jq -s add > /tmp/artifacts/data.json
          
          stat data.json || echo "[]" > data.json
          jq -s '.[0] + .[1]' data.json /tmp/artifacts/data.json > /tmp/artifacts/mix.json
          mv /tmp/artifacts/mix.json data.json
          
          cp /tmp/artifacts/*.json.gz reports
      - name: Commit the report results
        uses: EndBug/add-and-commit@v4
        with:
          add: "*.json reports"
          ref: reports
          message: Add reports
          author_name: "GitHub Actions"
          author_email: "actions@github.com"
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Send the reports to Slack
        uses: rtCamp/action-slack-notify@v2.1.0
        env:
          SLACK_CHANNEL: 'devops'
          SLACK_COLOR: 'good'
          SLACK_ICON: ':face_with_monocle:'
          SLACK_MESSAGE: |
            To be done
          SLACK_FOOTER: |
            <https://github.com/helpfulengineering/lighthouse/blob/master/.github/workflows/report.yml|Click here to modify this bot.>
          SLACK_TITLE: 'Metrics for helpfulengineering.org'
          SLACK_USERNAME: 'Lighthouse'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          MSG_MINIMAL: true
